{
  "stats": {
    "suites": 0,
    "tests": 1,
    "passes": 0,
    "pending": 0,
    "failures": 1,
    "start": "2021-03-05T05:56:28.171Z",
    "end": "2021-03-05T05:56:53.601Z",
    "duration": 25430,
    "testsRegistered": 1,
    "passPercent": 0,
    "pendingPercent": 0,
    "other": 0,
    "hasOther": false,
    "skipped": 0,
    "hasSkipped": false
  },
  "results": [
    {
      "uuid": "68cb9f67-a5f5-44b5-92c3-10fdf6a45d45",
      "title": "",
      "fullFile": "cypress\\integration\\basic.ts",
      "file": "cypress\\integration\\basic.ts",
      "beforeHooks": [],
      "afterHooks": [],
      "tests": [
        {
          "title": "assertion demo",
          "fullTitle": "assertion demo",
          "timedOut": null,
          "duration": 22620,
          "state": "failed",
          "speed": null,
          "pass": false,
          "fail": true,
          "pending": false,
          "context": "{\n  \"title\": \"Failed screenshot\",\n  \"value\": \"screenshots\\\\basic.ts\\\\assertion demo (failed).png\"\n}",
          "code": "cy.log('Start');\ncy.visit('https://example.cypress.io/');\ncy.contains('get').click();\ncy.get('#query-btn').should('contain', 'Button');\n// should('have.class','query-btn').should('be.visible').should('be.enabled')\n// cy.get('#query-btn').invoke('attr','id').should('equal','query-btn')\n// cy.get('#query-btn').should('contain','button').and('have.class','query-btn')\nexpect(true).to.be.true;\nvar name = 'cypress';\nexpect(name).to.be.equal('cypress');\nassert.equal(4, 4, \"Not Equal\");",
          "err": {
            "message": "ReferenceError: The following error originated from your application code, not from Cypress.\n\n  > hljs is not defined\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application",
            "estack": "ReferenceError: The following error originated from your application code, not from Cypress.\n\n  > hljs is not defined\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at https://example.cypress.io/assets/js/scripts.4a26d59a.js:4:1",
            "diff": null
          },
          "uuid": "935e0c1c-f7d9-49d5-91da-107892595aa3",
          "parentUUID": "68cb9f67-a5f5-44b5-92c3-10fdf6a45d45",
          "isHook": false,
          "skipped": false
        }
      ],
      "suites": [],
      "passes": [],
      "failures": [
        "935e0c1c-f7d9-49d5-91da-107892595aa3"
      ],
      "pending": [],
      "skipped": [],
      "duration": 22620,
      "root": true,
      "rootEmpty": false,
      "_timeout": 2000
    }
  ],
  "meta": {
    "mocha": {
      "version": "7.0.1"
    },
    "mochawesome": {
      "options": {
        "quiet": false,
        "reportFilename": "mochawesome",
        "saveHtml": false,
        "saveJson": true,
        "consoleReporter": "spec",
        "useInlineDiffs": false,
        "code": true
      },
      "version": "6.2.2"
    },
    "marge": {
      "options": {
        "reportDir": "cypress/results/json",
        "overwrite": false,
        "html": false,
        "json": true
      },
      "version": "5.2.0"
    }
  }
}